input_size: 3072
hidden_sizes: [512, 256, 128]
output_size: 10

num_epochs: 75

classes:
  [
    "plane",
    "car",
    "bird",
    "cat",
    "deer",
    "dog",
    "frog",
    "horse",
    "ship",
    "truck",
  ]
